[package]
name = "randomizer"
version = "0.1.0"
edition = "2024"

[dependencies]
jni = "0.21.1"

[lib]
# cf. https://doc.rust-lang.org/reference/linkage.html
crate-type = ["cdylib"]

[profile.release]
lto = true
